version: '3.9'

services:
  mysql:
    image: mysql:8.4.3
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
  mongodb:
    image: mongo:6.0.20
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
    volumes:
      - ./mongodb:/data/db
    env_file:
      - .env

networks:
  backend:
