version: '3.9'

services:
  mysql:
    image: mysql:8.4.3
    restart: always
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost | grep 'mysqld is alive' || exit 1"]
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env
  mongodb:
    image: mongo:6.0.20
    restart: always
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })' | grep 'ok' || exit 1"]
    volumes:
      - ./mongodb:/data/db
    env_file:
      - .env
  web:
    build: .
    restart: always
    depends_on:
      - mysql
      - mongodb
    networks:
      - internal_network
      - external_network
    ports:
      - "127.0.0.1:8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health | grep 'ok' || exit 1"]
    env_file:
      - .env

networks:
  external_network:
    driver: bridge
  internal_network:
    internal: true
